In [2]:
import pandas as pd
import seaborn as sns
import numpy as np

In [265]:
#display all columns and rows
pd.set_option('display.max_columns', 30)
pd.set_option('display.max_rows', 30)

In [281]:
#Load the dataset into a Pandas DataFrame.
df = pd.read_csv("./datasets/tripadvisor-rating-impact-on-hotel-popularity/data_rdd.csv", encoding_errors="ignore")

In [43]:
#Show df summary information.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4599 entries, 0 to 4598
Columns: 272 entries, Unnamed: 0 to amenities_Yoga classes
dtypes: float64(8), int64(261), object(3)
memory usage: 9.5+ MB

In [ ]:
#Show stats info on numerical columns.
df.describe()

In [ ]:
#Display the first few rows of the DataFrame.
df.head(10)

In [ ]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [ ]:
#Check the data types of each column.
df.dtypes

In [ ]:
#Handling Missing Values:
	#Identify missing values in the dataset.
		#Count the number of missing values in each column.

for column in df.columns:
    print("Column", column, "has", df[column].isna().sum(), "empty values.")

In [ ]:
#Show rows with missing values on a specific column name.
df[df["photos"].isna()][["name", "photos"]]

In [ ]:
#Replace NaN values in any column with the previous value.
df["photos"].ffill(inplace=True)

In [9]:
#Replace NaN values in two or more columns . location_grade, price_curr_min, price_min 
df.fillna({"location_grade" : df["location_grade"].mean(), "price_curr_min": df["price_curr_min"].max(), "price_min": df["price_min"].min()}, inplace=True)

In [13]:
#Delete rows 
		#with all columns empty values.
df.dropna(how="all")

,Unnamed: 0,hotel_url,name,views,views_binary,score_adjusted,bubble_rating,category_hotel,category_inn,category_specialty,...,amenities_Wardrobe / closet,amenities_Washing machine,amenities_Water park,amenities_Water park offsite,amenities_Waterslide,amenities_Waxing services,amenities_Whirlpool bathtub,amenities_Wifi,amenities_Wine / champagne,amenities_Yoga classes
0,1,https://www.tripadvisor.com/Hotel_Review-g1877...,Casa Mia in Trastevere,0,0,4.409091,4.5,0,1,0,...,0,0,0,0,0,0,0,1,1,0
1,2,https://www.tripadvisor.com/Hotel_Review-g1877...,Hotel Artemide,88,1,4.798118,5.0,1,0,0,...,1,1,0,0,0,0,0,1,0,0
2,3,https://www.tripadvisor.com/Hotel_Review-g1877...,A.Roma Lifestyle Hotel,32,1,4.634085,4.5,1,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,https://www.tripadvisor.com/Hotel_Review-g1877...,iQ Hotel Roma,17,1,4.699138,4.5,1,0,0,...,1,1,0,0,0,0,0,1,1,0
4,5,https://www.tripadvisor.com/Hotel_Review-g1877...,The Guardian,0,0,4.624299,4.5,1,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4594,4595,https://www.tripadvisor.com/Hotel_Review-g1877...,Residence Libetta,0,0,1.733333,1.5,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4595,4596,https://www.tripadvisor.com/Hotel_Review-g1877...,Hotel Divine Rome,0,0,1.888889,2.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4596,4597,https://www.tripadvisor.com/Hotel_Review-g1877...,Best Location in Rome,0,0,2.090909,2.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4597,4598,https://www.tripadvisor.com/Hotel_Review-g1877...,Albatros Vittoria Vaticano,0,0,2.000000,2.0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4598,4599,https://www.tripadvisor.com/Hotel_Review-g1877...,Hotel Quisisana,0,0,1.686170,1.5,1,0,0,...,0,0,0,0,0,0,0,1,0,0

In [9]:
#Delete rows 
		#with empty values in any column.
df.dropna(how="any", inplace=True)

(2262, 272)

In [121]:
#Impute missing numerical values.
		#Mean Imputation: Replace missing values with the mean (average) value of the non-missing values in the same column. 

#view column types and nan values for each column.
for column in df.columns:
    print("Column", column, "is", df[column].dtypes, "and has", df[column].isna().sum() , "nan values.")

#will use price_min
df["price_min"].fillna(df["price_min"].mean(), inplace=True)

print("\n\nNow, column price_min has", df["price_min"].isna().sum(), "nan values.")

df["price_min"]

Column Unnamed: 0 is int64 and has 0 nan values.
Column hotel_url is object and has 0 nan values.
Column name is object and has 0 nan values.
Column views is int64 and has 0 nan values.
Column views_binary is int64 and has 0 nan values.
Column score_adjusted is float64 and has 0 nan values.
Column bubble_rating is float64 and has 0 nan values.
Column category_hotel is int64 and has 0 nan values.
Column category_inn is int64 and has 0 nan values.
Column category_specialty is int64 and has 0 nan values.
Column class is object and has 0 nan values.
Column class_4_5 is int64 and has 0 nan values.
Column class_3_4_5 is int64 and has 0 nan values.
Column n_reviews is int64 and has 0 nan values.
Column location_grade is float64 and has 218 nan values.
Column discount is int64 and has 0 nan values.
Column discount_perc is float64 and has 0 nan values.
Column price_curr_min is float64 and has 2224 nan values.
Column price_min is float64 and has 1125 nan values.
Column price_max is float64 and has 1127 nan values.
Column award_travellers_choice is int64 and has 0 nan values.
Column award_greenleaders is int64 and has 0 nan values.
Column award_cert_excellence is int64 and has 0 nan values.
Column photos is float64 and has 577 nan values.
Column amenities_24-hour check-in is int64 and has 0 nan values.
Column amenities_24-hour front desk is int64 and has 0 nan values.
Column amenities_24-hour security is int64 and has 0 nan values.
Column amenities_Additional bathroom is int64 and has 0 nan values.
Column amenities_Adults only is int64 and has 0 nan values.
Column amenities_Aerobics is int64 and has 0 nan values.
Column amenities_Air conditioning is int64 and has 0 nan values.
Column amenities_Air purifier is int64 and has 0 nan values.
Column amenities_Airport transportation is int64 and has 0 nan values.
Column amenities_Allergy-free room is int64 and has 0 nan values.
Column amenities_amenity_free_internet_title_ad3 is int64 and has 0 nan values.
Column amenities_ATM on site is int64 and has 0 nan values.
Column amenities_Babysitting is int64 and has 0 nan values.
Column amenities_Baggage storage is int64 and has 0 nan values.
Column amenities_Banquet room is int64 and has 0 nan values.
Column amenities_Bar / lounge is int64 and has 0 nan values.
Column amenities_Bath / shower is int64 and has 0 nan values.
Column amenities_Bathrobes is int64 and has 0 nan values.
Column amenities_BBQ facilities is int64 and has 0 nan values.
Column amenities_Beach is int64 and has 0 nan values.
Column amenities_Bicycle rental is int64 and has 0 nan values.
Column amenities_Bicycle tours is int64 and has 0 nan values.
Column amenities_Bicycles available is int64 and has 0 nan values.
Column amenities_Bidet is int64 and has 0 nan values.
Column amenities_Billiards is int64 and has 0 nan values.
Column amenities_Blackout curtains is int64 and has 0 nan values.
Column amenities_Board games / puzzles is int64 and has 0 nan values.
Column amenities_Body wrap is int64 and has 0 nan values.
Column amenities_Books, DVDs, music for children is int64 and has 0 nan values.
Column amenities_Bottled water is int64 and has 0 nan values.
Column amenities_Bowling is int64 and has 0 nan values.
Column amenities_Bowling offsite is int64 and has 0 nan values.
Column amenities_Breakfast available is int64 and has 0 nan values.
Column amenities_Breakfast buffet is int64 and has 0 nan values.
Column amenities_Breakfast in the room is int64 and has 0 nan values.
Column amenities_Bridal suite is int64 and has 0 nan values.
Column amenities_Business Center with Internet Access is int64 and has 0 nan values.
Column amenities_Butler service is int64 and has 0 nan values.
Column amenities_Cable / satellite TV is int64 and has 0 nan values.
Column amenities_Canoeing is int64 and has 0 nan values.
Column amenities_Canoeing offsite is int64 and has 0 nan values.
Column amenities_Car hire is int64 and has 0 nan values.
Column amenities_Casino and Gambling is int64 and has 0 nan values.
Column amenities_Chapel / shrine is int64 and has 0 nan values.
Column amenities_Children's playground is int64 and has 0 nan values.
Column amenities_Children's television networks is int64 and has 0 nan values.
Column amenities_Children Activities (Kid / Family Friendly) is int64 and has 0 nan values.
Column amenities_City view is int64 and has 0 nan values.
Column amenities_Clothes dryer is int64 and has 0 nan values.
Column amenities_Clothes rack is int64 and has 0 nan values.
Column amenities_Coffee / tea maker is int64 and has 0 nan values.
Column amenities_Coffee shop is int64 and has 0 nan values.
Column amenities_Complimentary instant cofffee is int64 and has 0 nan values.
Column amenities_Complimentary tea is int64 and has 0 nan values.
Column amenities_Complimentary toiletries is int64 and has 0 nan values.
Column amenities_Complimentary welcome drink is int64 and has 0 nan values.
Column amenities_Concierge is int64 and has 0 nan values.
Column amenities_Conference facilities is int64 and has 0 nan values.
Column amenities_Convenience store is int64 and has 0 nan values.
Column amenities_Couples massage is int64 and has 0 nan values.
Column amenities_Currency exchange is int64 and has 0 nan values.
Column amenities_Darts is int64 and has 0 nan values.
Column amenities_Desk is int64 and has 0 nan values.
Column amenities_Dining area is int64 and has 0 nan values.
Column amenities_Dishwasher is int64 and has 0 nan values.
Column amenities_Diving is int64 and has 0 nan values.
Column amenities_Doorperson is int64 and has 0 nan values.
Column amenities_Dry cleaning is int64 and has 0 nan values.
Column amenities_DVD / CD player is int64 and has 0 nan values.
Column amenities_Electric blanket is int64 and has 0 nan values.
Column amenities_Electric kettle is int64 and has 0 nan values.
Column amenities_Electric vehicle charging station is int64 and has 0 nan values.
Column amenities_Entertainment staff is int64 and has 0 nan values.
Column amenities_Evening entertainment is int64 and has 0 nan values.
Column amenities_Executive lounge access is int64 and has 0 nan values.
Column amenities_Express check-in / check-out is int64 and has 0 nan values.
Column amenities_Extra long beds is int64 and has 0 nan values.
Column amenities_Facial treatments is int64 and has 0 nan values.
Column amenities_Family rooms is int64 and has 0 nan values.
Column amenities_Fax / photocopying is int64 and has 0 nan values.
Column amenities_Fence around pool is int64 and has 0 nan values.
Column amenities_Fireplace is int64 and has 0 nan values.
Column amenities_First aid kit is int64 and has 0 nan values.
Column amenities_Fishing is int64 and has 0 nan values.
Column amenities_Fitness / spa locker rooms is int64 and has 0 nan values.
Column amenities_Fitness Center with Gym / Workout Room is int64 and has 0 nan values.
Column amenities_Fitness classes is int64 and has 0 nan values.
Column amenities_Flatscreen TV is int64 and has 0 nan values.
Column amenities_Foot bath is int64 and has 0 nan values.
Column amenities_Foot massage is int64 and has 0 nan values.
Column amenities_Free airport transportation is int64 and has 0 nan values.
Column amenities_Free breakfast is int64 and has 0 nan values.
Column amenities_Free High Speed Internet (WiFi) is int64 and has 0 nan values.
Column amenities_Free internet is int64 and has 0 nan values.
Column amenities_Free parking is int64 and has 0 nan values.
Column amenities_Free private parking nearby is int64 and has 0 nan values.
Column amenities_Free public parking nearby is int64 and has 0 nan values.
Column amenities_Free shuttle or taxi services is int64 and has 0 nan values.
Column amenities_Free wifi in the business center is int64 and has 0 nan values.
Column amenities_Free wired internet in the business center is int64 and has 0 nan values.
Column amenities_Full body massage is int64 and has 0 nan values.
Column amenities_Game room is int64 and has 0 nan values.
Column amenities_Gift shop is int64 and has 0 nan values.
Column amenities_Golf course is int64 and has 0 nan values.
Column amenities_Hair dryer is int64 and has 0 nan values.
Column amenities_Hammam is int64 and has 0 nan values.
Column amenities_Hand massage is int64 and has 0 nan values.
Column amenities_Happy hour is int64 and has 0 nan values.
Column amenities_Head massage is int64 and has 0 nan values.
Column amenities_Heated pool is int64 and has 0 nan values.
Column amenities_Highchairs available is int64 and has 0 nan values.
Column amenities_Hiking is int64 and has 0 nan values.
Column amenities_Horseback riding is int64 and has 0 nan values.
Column amenities_Hot tub is int64 and has 0 nan values.
Column amenities_hotel_amenity_free_breakfast is int64 and has 0 nan values.
Column amenities_hotel_amenity_free_internet is int64 and has 0 nan values.
Column amenities_hotel_amenity_internet is int64 and has 0 nan values.
Column amenities_hotel_amenity_wifi is int64 and has 0 nan values.
Column amenities_Housekeeping is int64 and has 0 nan values.
Column amenities_Indoor play area for children is int64 and has 0 nan values.
Column amenities_Indoor pool is int64 and has 0 nan values.
Column amenities_Interconnected rooms available is int64 and has 0 nan values.
Column amenities_Internet is int64 and has 0 nan values.
Column amenities_iPod docking station is int64 and has 0 nan values.
Column amenities_Iron is int64 and has 0 nan values.
Column amenities_Ironing service is int64 and has 0 nan values.
Column amenities_Karaoke is int64 and has 0 nan values.
Column amenities_Kid-friendly buffet is int64 and has 0 nan values.
Column amenities_Kids' meals is int64 and has 0 nan values.
Column amenities_Kids' outdoor play equipment is int64 and has 0 nan values.
Column amenities_Kids club is int64 and has 0 nan values.
Column amenities_Kids pool is int64 and has 0 nan values.
Column amenities_Kids stay free is int64 and has 0 nan values.
Column amenities_Kitchenette is int64 and has 0 nan values.
Column amenities_Kitchenware is int64 and has 0 nan values.
Column amenities_Landmark view is int64 and has 0 nan values.
Column amenities_Laptop safe is int64 and has 0 nan values.
Column amenities_Laundry service is int64 and has 0 nan values.
Column amenities_Makeup services is int64 and has 0 nan values.
Column amenities_Manicure is int64 and has 0 nan values.
Column amenities_Massage is int64 and has 0 nan values.
Column amenities_Massage chair is int64 and has 0 nan values.
Column amenities_Meeting rooms is int64 and has 0 nan values.
Column amenities_Microwave is int64 and has 0 nan values.
Column amenities_Mini golf is int64 and has 0 nan values.
Column amenities_Minibar is int64 and has 0 nan values.
Column amenities_Mosquito net is int64 and has 0 nan values.
Column amenities_Neck massage is int64 and has 0 nan values.
Column amenities_Newspaper is int64 and has 0 nan values.
Column amenities_Nightclub / DJ is int64 and has 0 nan values.
Column amenities_Non-smoking hotel is int64 and has 0 nan values.
Column amenities_Non-smoking rooms is int64 and has 0 nan values.
Column amenities_On-demand movies is int64 and has 0 nan values.
Column amenities_Open-air bath is int64 and has 0 nan values.
Column amenities_Outdoor dining area is int64 and has 0 nan values.
Column amenities_Outdoor fireplace is int64 and has 0 nan values.
Column amenities_Outdoor furniture is int64 and has 0 nan values.
Column amenities_Outdoor pool is int64 and has 0 nan values.
Column amenities_Oven is int64 and has 0 nan values.
Column amenities_Paid internet is int64 and has 0 nan values.
Column amenities_Paid private parking nearby is int64 and has 0 nan values.
Column amenities_Paid private parking on-site is int64 and has 0 nan values.
Column amenities_Paid public parking nearby is int64 and has 0 nan values.
Column amenities_Paid public parking on-site is int64 and has 0 nan values.
Column amenities_Paid wifi is int64 and has 0 nan values.
Column amenities_Parking is int64 and has 0 nan values.
Column amenities_Parking garage is int64 and has 0 nan values.
Column amenities_Patio is int64 and has 0 nan values.
Column amenities_Pedicure is int64 and has 0 nan values.
Column amenities_Personal trainer is int64 and has 0 nan values.
Column amenities_Pets Allowed ( Dog / Pet Friendly ) is int64 and has 0 nan values.
Column amenities_Photo copier / fax In business center is int64 and has 0 nan values.
Column amenities_Picnic area is int64 and has 0 nan values.
Column amenities_Plunge pool is int64 and has 0 nan values.
Column amenities_Pool is int64 and has 0 nan values.
Column amenities_Pool / beach towels is int64 and has 0 nan values.
Column amenities_Pool with view is int64 and has 0 nan values.
Column amenities_Poolside bar is int64 and has 0 nan values.
Column amenities_Private balcony is int64 and has 0 nan values.
Column amenities_Private bathrooms is int64 and has 0 nan values.
Column amenities_Private check-in / check-out is int64 and has 0 nan values.
Column amenities_Private pool is int64 and has 0 nan values.
Column amenities_Public wifi is int64 and has 0 nan values.
Column amenities_Radio is int64 and has 0 nan values.
Column amenities_Refrigerator is int64 and has 0 nan values.
Column amenities_Restaurant is int64 and has 0 nan values.
Column amenities_Rooftop bar is int64 and has 0 nan values.
Column amenities_Rooftop pool is int64 and has 0 nan values.
Column amenities_Rooftop terrace is int64 and has 0 nan values.
Column amenities_Room service is int64 and has 0 nan values.
Column amenities_Safe is int64 and has 0 nan values.
Column amenities_Salon is int64 and has 0 nan values.
Column amenities_Saltwater pool is int64 and has 0 nan values.
Column amenities_Sauna is int64 and has 0 nan values.
Column amenities_Seating area is int64 and has 0 nan values.
Column amenities_Secured parking is int64 and has 0 nan values.
Column amenities_Self-serve laundry is int64 and has 0 nan values.
Column amenities_Separate dining area is int64 and has 0 nan values.
Column amenities_Separate living room is int64 and has 0 nan values.
Column amenities_Shallow end in pool is int64 and has 0 nan values.
Column amenities_Shared bathroom is int64 and has 0 nan values.
Column amenities_Shared kitchen is int64 and has 0 nan values.
Column amenities_Shared lounge / TV area is int64 and has 0 nan values.
Column amenities_Shoeshine is int64 and has 0 nan values.
Column amenities_Shops is int64 and has 0 nan values.
Column amenities_Shuttle bus service is int64 and has 0 nan values.
Column amenities_Smoking rooms available is int64 and has 0 nan values.
Column amenities_Snack bar is int64 and has 0 nan values.
Column amenities_Sofa is int64 and has 0 nan values.
Column amenities_Sofa bed is int64 and has 0 nan values.
Column amenities_Solarium is int64 and has 0 nan values.
Column amenities_Soundproof rooms is int64 and has 0 nan values.
Column amenities_Spa is int64 and has 0 nan values.
Column amenities_Special diet menus is int64 and has 0 nan values.
Column amenities_Steam room is int64 and has 0 nan values.
Column amenities_Stovetop is int64 and has 0 nan values.
Column amenities_Street parking is int64 and has 0 nan values.
Column amenities_Strollers is int64 and has 0 nan values.
Column amenities_Suites is int64 and has 0 nan values.
Column amenities_Sun deck is int64 and has 0 nan values.
Column amenities_Sun loungers / beach chairs is int64 and has 0 nan values.
Column amenities_Sun terrace is int64 and has 0 nan values.
Column amenities_Sun umbrellas is int64 and has 0 nan values.
Column amenities_Swimup bar is int64 and has 0 nan values.
Column amenities_Table tennis is int64 and has 0 nan values.
Column amenities_Taxi service is int64 and has 0 nan values.
Column amenities_Telephone is int64 and has 0 nan values.
Column amenities_Tennis court is int64 and has 0 nan values.
Column amenities_Tennis court offsite is int64 and has 0 nan values.
Column amenities_Tile / marble floor is int64 and has 0 nan values.
Column amenities_Umbrella is int64 and has 0 nan values.
Column amenities_Valet parking is int64 and has 0 nan values.
Column amenities_Vending machine is int64 and has 0 nan values.
Column amenities_Video game console is int64 and has 0 nan values.
Column amenities_VIP room facilities is int64 and has 0 nan values.
Column amenities_Wake-up service / alarm clock is int64 and has 0 nan values.
Column amenities_Walk-in shower is int64 and has 0 nan values.
Column amenities_Walking tours is int64 and has 0 nan values.
Column amenities_Wardrobe / closet is int64 and has 0 nan values.
Column amenities_Washing machine is int64 and has 0 nan values.
Column amenities_Water park is int64 and has 0 nan values.
Column amenities_Water park offsite is int64 and has 0 nan values.
Column amenities_Waterslide is int64 and has 0 nan values.
Column amenities_Waxing services is int64 and has 0 nan values.
Column amenities_Whirlpool bathtub is int64 and has 0 nan values.
Column amenities_Wifi is int64 and has 0 nan values.
Column amenities_Wine / champagne is int64 and has 0 nan values.
Column amenities_Yoga classes is int64 and has 0 nan values.


Now, column price_min has 0 nan values.

0        5502.000000
1       10949.000000
2        8381.000000
3        7703.000000
4        4606.000000
            ...
4594     7236.000000
4595     2754.000000
4596     5072.767415
4597     5072.767415
4598     5072.767415
Name: price_min, Length: 4599, dtype: float64

In [34]:
#Median Imputation: Replace missing values with the median value of the non-missing values in the same column. 
		#This is less sensitive to outliers compared to mean imputation.

#Check for numeric columns and nan values 
for column in df.columns:
    print("Column", column, "is", df[column].dtypes, "and has", df[column].isna().sum(), "nan values.")

#will use price-max
df["price_max"].fillna(df["price_max"].median(), inplace=True)

#check for results
print("\nColumn price-max has", df["price_max"].isna().sum(), "nan values.")

Column Unnamed: 0 is int64 and has 0 nan values.
Column hotel_url is object and has 0 nan values.
Column name is object and has 0 nan values.
Column views is int64 and has 0 nan values.
Column views_binary is int64 and has 0 nan values.
Column score_adjusted is float64 and has 0 nan values.
Column bubble_rating is float64 and has 0 nan values.
Column category_hotel is int64 and has 0 nan values.
Column category_inn is int64 and has 0 nan values.
Column category_specialty is int64 and has 0 nan values.
Column class is object and has 0 nan values.
Column class_4_5 is int64 and has 0 nan values.
Column class_3_4_5 is int64 and has 0 nan values.
Column n_reviews is int64 and has 0 nan values.
Column location_grade is float64 and has 218 nan values.
Column discount is int64 and has 0 nan values.
Column discount_perc is float64 and has 0 nan values.
Column price_curr_min is float64 and has 2224 nan values.
Column price_min is float64 and has 1125 nan values.
Column price_max is float64 and has 1127 nan values.
Column award_travellers_choice is int64 and has 0 nan values.
Column award_greenleaders is int64 and has 0 nan values.
Column award_cert_excellence is int64 and has 0 nan values.
Column photos is float64 and has 577 nan values.
Column amenities_24-hour check-in is int64 and has 0 nan values.
Column amenities_24-hour front desk is int64 and has 0 nan values.
Column amenities_24-hour security is int64 and has 0 nan values.
Column amenities_Additional bathroom is int64 and has 0 nan values.
Column amenities_Adults only is int64 and has 0 nan values.
Column amenities_Aerobics is int64 and has 0 nan values.
Column amenities_Air conditioning is int64 and has 0 nan values.
Column amenities_Air purifier is int64 and has 0 nan values.
Column amenities_Airport transportation is int64 and has 0 nan values.
Column amenities_Allergy-free room is int64 and has 0 nan values.
Column amenities_amenity_free_internet_title_ad3 is int64 and has 0 nan values.
Column amenities_ATM on site is int64 and has 0 nan values.
Column amenities_Babysitting is int64 and has 0 nan values.
Column amenities_Baggage storage is int64 and has 0 nan values.
Column amenities_Banquet room is int64 and has 0 nan values.
Column amenities_Bar / lounge is int64 and has 0 nan values.
Column amenities_Bath / shower is int64 and has 0 nan values.
Column amenities_Bathrobes is int64 and has 0 nan values.
Column amenities_BBQ facilities is int64 and has 0 nan values.
Column amenities_Beach is int64 and has 0 nan values.
Column amenities_Bicycle rental is int64 and has 0 nan values.
Column amenities_Bicycle tours is int64 and has 0 nan values.
Column amenities_Bicycles available is int64 and has 0 nan values.
Column amenities_Bidet is int64 and has 0 nan values.
Column amenities_Billiards is int64 and has 0 nan values.
Column amenities_Blackout curtains is int64 and has 0 nan values.
Column amenities_Board games / puzzles is int64 and has 0 nan values.
Column amenities_Body wrap is int64 and has 0 nan values.
Column amenities_Books, DVDs, music for children is int64 and has 0 nan values.
Column amenities_Bottled water is int64 and has 0 nan values.
Column amenities_Bowling is int64 and has 0 nan values.
Column amenities_Bowling offsite is int64 and has 0 nan values.
Column amenities_Breakfast available is int64 and has 0 nan values.
Column amenities_Breakfast buffet is int64 and has 0 nan values.
Column amenities_Breakfast in the room is int64 and has 0 nan values.
Column amenities_Bridal suite is int64 and has 0 nan values.
Column amenities_Business Center with Internet Access is int64 and has 0 nan values.
Column amenities_Butler service is int64 and has 0 nan values.
Column amenities_Cable / satellite TV is int64 and has 0 nan values.
Column amenities_Canoeing is int64 and has 0 nan values.
Column amenities_Canoeing offsite is int64 and has 0 nan values.
Column amenities_Car hire is int64 and has 0 nan values.
Column amenities_Casino and Gambling is int64 and has 0 nan values.
Column amenities_Chapel / shrine is int64 and has 0 nan values.
Column amenities_Children's playground is int64 and has 0 nan values.
Column amenities_Children's television networks is int64 and has 0 nan values.
Column amenities_Children Activities (Kid / Family Friendly) is int64 and has 0 nan values.
Column amenities_City view is int64 and has 0 nan values.
Column amenities_Clothes dryer is int64 and has 0 nan values.
Column amenities_Clothes rack is int64 and has 0 nan values.
Column amenities_Coffee / tea maker is int64 and has 0 nan values.
Column amenities_Coffee shop is int64 and has 0 nan values.
Column amenities_Complimentary instant cofffee is int64 and has 0 nan values.
Column amenities_Complimentary tea is int64 and has 0 nan values.
Column amenities_Complimentary toiletries is int64 and has 0 nan values.
Column amenities_Complimentary welcome drink is int64 and has 0 nan values.
Column amenities_Concierge is int64 and has 0 nan values.
Column amenities_Conference facilities is int64 and has 0 nan values.
Column amenities_Convenience store is int64 and has 0 nan values.
Column amenities_Couples massage is int64 and has 0 nan values.
Column amenities_Currency exchange is int64 and has 0 nan values.
Column amenities_Darts is int64 and has 0 nan values.
Column amenities_Desk is int64 and has 0 nan values.
Column amenities_Dining area is int64 and has 0 nan values.
Column amenities_Dishwasher is int64 and has 0 nan values.
Column amenities_Diving is int64 and has 0 nan values.
Column amenities_Doorperson is int64 and has 0 nan values.
Column amenities_Dry cleaning is int64 and has 0 nan values.
Column amenities_DVD / CD player is int64 and has 0 nan values.
Column amenities_Electric blanket is int64 and has 0 nan values.
Column amenities_Electric kettle is int64 and has 0 nan values.
Column amenities_Electric vehicle charging station is int64 and has 0 nan values.
Column amenities_Entertainment staff is int64 and has 0 nan values.
Column amenities_Evening entertainment is int64 and has 0 nan values.
Column amenities_Executive lounge access is int64 and has 0 nan values.
Column amenities_Express check-in / check-out is int64 and has 0 nan values.
Column amenities_Extra long beds is int64 and has 0 nan values.
Column amenities_Facial treatments is int64 and has 0 nan values.
Column amenities_Family rooms is int64 and has 0 nan values.
Column amenities_Fax / photocopying is int64 and has 0 nan values.
Column amenities_Fence around pool is int64 and has 0 nan values.
Column amenities_Fireplace is int64 and has 0 nan values.
Column amenities_First aid kit is int64 and has 0 nan values.
Column amenities_Fishing is int64 and has 0 nan values.
Column amenities_Fitness / spa locker rooms is int64 and has 0 nan values.
Column amenities_Fitness Center with Gym / Workout Room is int64 and has 0 nan values.
Column amenities_Fitness classes is int64 and has 0 nan values.
Column amenities_Flatscreen TV is int64 and has 0 nan values.
Column amenities_Foot bath is int64 and has 0 nan values.
Column amenities_Foot massage is int64 and has 0 nan values.
Column amenities_Free airport transportation is int64 and has 0 nan values.
Column amenities_Free breakfast is int64 and has 0 nan values.
Column amenities_Free High Speed Internet (WiFi) is int64 and has 0 nan values.
Column amenities_Free internet is int64 and has 0 nan values.
Column amenities_Free parking is int64 and has 0 nan values.
Column amenities_Free private parking nearby is int64 and has 0 nan values.
Column amenities_Free public parking nearby is int64 and has 0 nan values.
Column amenities_Free shuttle or taxi services is int64 and has 0 nan values.
Column amenities_Free wifi in the business center is int64 and has 0 nan values.
Column amenities_Free wired internet in the business center is int64 and has 0 nan values.
Column amenities_Full body massage is int64 and has 0 nan values.
Column amenities_Game room is int64 and has 0 nan values.
Column amenities_Gift shop is int64 and has 0 nan values.
Column amenities_Golf course is int64 and has 0 nan values.
Column amenities_Hair dryer is int64 and has 0 nan values.
Column amenities_Hammam is int64 and has 0 nan values.
Column amenities_Hand massage is int64 and has 0 nan values.
Column amenities_Happy hour is int64 and has 0 nan values.
Column amenities_Head massage is int64 and has 0 nan values.
Column amenities_Heated pool is int64 and has 0 nan values.
Column amenities_Highchairs available is int64 and has 0 nan values.
Column amenities_Hiking is int64 and has 0 nan values.
Column amenities_Horseback riding is int64 and has 0 nan values.
Column amenities_Hot tub is int64 and has 0 nan values.
Column amenities_hotel_amenity_free_breakfast is int64 and has 0 nan values.
Column amenities_hotel_amenity_free_internet is int64 and has 0 nan values.
Column amenities_hotel_amenity_internet is int64 and has 0 nan values.
Column amenities_hotel_amenity_wifi is int64 and has 0 nan values.
Column amenities_Housekeeping is int64 and has 0 nan values.
Column amenities_Indoor play area for children is int64 and has 0 nan values.
Column amenities_Indoor pool is int64 and has 0 nan values.
Column amenities_Interconnected rooms available is int64 and has 0 nan values.
Column amenities_Internet is int64 and has 0 nan values.
Column amenities_iPod docking station is int64 and has 0 nan values.
Column amenities_Iron is int64 and has 0 nan values.
Column amenities_Ironing service is int64 and has 0 nan values.
Column amenities_Karaoke is int64 and has 0 nan values.
Column amenities_Kid-friendly buffet is int64 and has 0 nan values.
Column amenities_Kids' meals is int64 and has 0 nan values.
Column amenities_Kids' outdoor play equipment is int64 and has 0 nan values.
Column amenities_Kids club is int64 and has 0 nan values.
Column amenities_Kids pool is int64 and has 0 nan values.
Column amenities_Kids stay free is int64 and has 0 nan values.
Column amenities_Kitchenette is int64 and has 0 nan values.
Column amenities_Kitchenware is int64 and has 0 nan values.
Column amenities_Landmark view is int64 and has 0 nan values.
Column amenities_Laptop safe is int64 and has 0 nan values.
Column amenities_Laundry service is int64 and has 0 nan values.
Column amenities_Makeup services is int64 and has 0 nan values.
Column amenities_Manicure is int64 and has 0 nan values.
Column amenities_Massage is int64 and has 0 nan values.
Column amenities_Massage chair is int64 and has 0 nan values.
Column amenities_Meeting rooms is int64 and has 0 nan values.
Column amenities_Microwave is int64 and has 0 nan values.
Column amenities_Mini golf is int64 and has 0 nan values.
Column amenities_Minibar is int64 and has 0 nan values.
Column amenities_Mosquito net is int64 and has 0 nan values.
Column amenities_Neck massage is int64 and has 0 nan values.
Column amenities_Newspaper is int64 and has 0 nan values.
Column amenities_Nightclub / DJ is int64 and has 0 nan values.
Column amenities_Non-smoking hotel is int64 and has 0 nan values.
Column amenities_Non-smoking rooms is int64 and has 0 nan values.
Column amenities_On-demand movies is int64 and has 0 nan values.
Column amenities_Open-air bath is int64 and has 0 nan values.
Column amenities_Outdoor dining area is int64 and has 0 nan values.
Column amenities_Outdoor fireplace is int64 and has 0 nan values.
Column amenities_Outdoor furniture is int64 and has 0 nan values.
Column amenities_Outdoor pool is int64 and has 0 nan values.
Column amenities_Oven is int64 and has 0 nan values.
Column amenities_Paid internet is int64 and has 0 nan values.
Column amenities_Paid private parking nearby is int64 and has 0 nan values.
Column amenities_Paid private parking on-site is int64 and has 0 nan values.
Column amenities_Paid public parking nearby is int64 and has 0 nan values.
Column amenities_Paid public parking on-site is int64 and has 0 nan values.
Column amenities_Paid wifi is int64 and has 0 nan values.
Column amenities_Parking is int64 and has 0 nan values.
Column amenities_Parking garage is int64 and has 0 nan values.
Column amenities_Patio is int64 and has 0 nan values.
Column amenities_Pedicure is int64 and has 0 nan values.
Column amenities_Personal trainer is int64 and has 0 nan values.
Column amenities_Pets Allowed ( Dog / Pet Friendly ) is int64 and has 0 nan values.
Column amenities_Photo copier / fax In business center is int64 and has 0 nan values.
Column amenities_Picnic area is int64 and has 0 nan values.
Column amenities_Plunge pool is int64 and has 0 nan values.
Column amenities_Pool is int64 and has 0 nan values.
Column amenities_Pool / beach towels is int64 and has 0 nan values.
Column amenities_Pool with view is int64 and has 0 nan values.
Column amenities_Poolside bar is int64 and has 0 nan values.
Column amenities_Private balcony is int64 and has 0 nan values.
Column amenities_Private bathrooms is int64 and has 0 nan values.
Column amenities_Private check-in / check-out is int64 and has 0 nan values.
Column amenities_Private pool is int64 and has 0 nan values.
Column amenities_Public wifi is int64 and has 0 nan values.
Column amenities_Radio is int64 and has 0 nan values.
Column amenities_Refrigerator is int64 and has 0 nan values.
Column amenities_Restaurant is int64 and has 0 nan values.
Column amenities_Rooftop bar is int64 and has 0 nan values.
Column amenities_Rooftop pool is int64 and has 0 nan values.
Column amenities_Rooftop terrace is int64 and has 0 nan values.
Column amenities_Room service is int64 and has 0 nan values.
Column amenities_Safe is int64 and has 0 nan values.
Column amenities_Salon is int64 and has 0 nan values.
Column amenities_Saltwater pool is int64 and has 0 nan values.
Column amenities_Sauna is int64 and has 0 nan values.
Column amenities_Seating area is int64 and has 0 nan values.
Column amenities_Secured parking is int64 and has 0 nan values.
Column amenities_Self-serve laundry is int64 and has 0 nan values.
Column amenities_Separate dining area is int64 and has 0 nan values.
Column amenities_Separate living room is int64 and has 0 nan values.
Column amenities_Shallow end in pool is int64 and has 0 nan values.
Column amenities_Shared bathroom is int64 and has 0 nan values.
Column amenities_Shared kitchen is int64 and has 0 nan values.
Column amenities_Shared lounge / TV area is int64 and has 0 nan values.
Column amenities_Shoeshine is int64 and has 0 nan values.
Column amenities_Shops is int64 and has 0 nan values.
Column amenities_Shuttle bus service is int64 and has 0 nan values.
Column amenities_Smoking rooms available is int64 and has 0 nan values.
Column amenities_Snack bar is int64 and has 0 nan values.
Column amenities_Sofa is int64 and has 0 nan values.
Column amenities_Sofa bed is int64 and has 0 nan values.
Column amenities_Solarium is int64 and has 0 nan values.
Column amenities_Soundproof rooms is int64 and has 0 nan values.
Column amenities_Spa is int64 and has 0 nan values.
Column amenities_Special diet menus is int64 and has 0 nan values.
Column amenities_Steam room is int64 and has 0 nan values.
Column amenities_Stovetop is int64 and has 0 nan values.
Column amenities_Street parking is int64 and has 0 nan values.
Column amenities_Strollers is int64 and has 0 nan values.
Column amenities_Suites is int64 and has 0 nan values.
Column amenities_Sun deck is int64 and has 0 nan values.
Column amenities_Sun loungers / beach chairs is int64 and has 0 nan values.
Column amenities_Sun terrace is int64 and has 0 nan values.
Column amenities_Sun umbrellas is int64 and has 0 nan values.
Column amenities_Swimup bar is int64 and has 0 nan values.
Column amenities_Table tennis is int64 and has 0 nan values.
Column amenities_Taxi service is int64 and has 0 nan values.
Column amenities_Telephone is int64 and has 0 nan values.
Column amenities_Tennis court is int64 and has 0 nan values.
Column amenities_Tennis court offsite is int64 and has 0 nan values.
Column amenities_Tile / marble floor is int64 and has 0 nan values.
Column amenities_Umbrella is int64 and has 0 nan values.
Column amenities_Valet parking is int64 and has 0 nan values.
Column amenities_Vending machine is int64 and has 0 nan values.
Column amenities_Video game console is int64 and has 0 nan values.
Column amenities_VIP room facilities is int64 and has 0 nan values.
Column amenities_Wake-up service / alarm clock is int64 and has 0 nan values.
Column amenities_Walk-in shower is int64 and has 0 nan values.
Column amenities_Walking tours is int64 and has 0 nan values.
Column amenities_Wardrobe / closet is int64 and has 0 nan values.
Column amenities_Washing machine is int64 and has 0 nan values.
Column amenities_Water park is int64 and has 0 nan values.
Column amenities_Water park offsite is int64 and has 0 nan values.
Column amenities_Waterslide is int64 and has 0 nan values.
Column amenities_Waxing services is int64 and has 0 nan values.
Column amenities_Whirlpool bathtub is int64 and has 0 nan values.
Column amenities_Wifi is int64 and has 0 nan values.
Column amenities_Wine / champagne is int64 and has 0 nan values.
Column amenities_Yoga classes is int64 and has 0 nan values.

Column price-max has 0 nan values.

In [42]:
#Mode Imputation: For discrete or categorical data, 
		#you can replace missing values with the mode (most frequent) value in the same column.

#Check for column types and nan values 
for column in df.columns:
    print("Column", column, "is", df[column].dtypes, "and has", df[column].isna().sum(), "nan values.")
    

#will use bubble_rating column
mode = df["bubble_rating"].mode()
df["bubble_rating"].fillna(mode[0])

#check for results
df["bubble_rating"].isna().sum()

Column Unnamed: 0 is int64 and has 0 nan values.
Column hotel_url is object and has 0 nan values.
Column name is object and has 0 nan values.
Column views is int64 and has 0 nan values.
Column views_binary is int64 and has 0 nan values.
Column score_adjusted is float64 and has 0 nan values.
Column bubble_rating is float64 and has 0 nan values.
Column category_hotel is int64 and has 0 nan values.
Column category_inn is int64 and has 0 nan values.
Column category_specialty is int64 and has 0 nan values.
Column class is object and has 0 nan values.
Column class_4_5 is int64 and has 0 nan values.
Column class_3_4_5 is int64 and has 0 nan values.
Column n_reviews is int64 and has 0 nan values.
Column location_grade is float64 and has 218 nan values.
Column discount is int64 and has 0 nan values.
Column discount_perc is float64 and has 0 nan values.
Column price_curr_min is float64 and has 2224 nan values.
Column price_min is float64 and has 1125 nan values.
Column price_max is float64 and has 0 nan values.
Column award_travellers_choice is int64 and has 0 nan values.
Column award_greenleaders is int64 and has 0 nan values.
Column award_cert_excellence is int64 and has 0 nan values.
Column photos is float64 and has 577 nan values.
Column amenities_24-hour check-in is int64 and has 0 nan values.
Column amenities_24-hour front desk is int64 and has 0 nan values.
Column amenities_24-hour security is int64 and has 0 nan values.
Column amenities_Additional bathroom is int64 and has 0 nan values.
Column amenities_Adults only is int64 and has 0 nan values.
Column amenities_Aerobics is int64 and has 0 nan values.
Column amenities_Air conditioning is int64 and has 0 nan values.
Column amenities_Air purifier is int64 and has 0 nan values.
Column amenities_Airport transportation is int64 and has 0 nan values.
Column amenities_Allergy-free room is int64 and has 0 nan values.
Column amenities_amenity_free_internet_title_ad3 is int64 and has 0 nan values.
Column amenities_ATM on site is int64 and has 0 nan values.
Column amenities_Babysitting is int64 and has 0 nan values.
Column amenities_Baggage storage is int64 and has 0 nan values.
Column amenities_Banquet room is int64 and has 0 nan values.
Column amenities_Bar / lounge is int64 and has 0 nan values.
Column amenities_Bath / shower is int64 and has 0 nan values.
Column amenities_Bathrobes is int64 and has 0 nan values.
Column amenities_BBQ facilities is int64 and has 0 nan values.
Column amenities_Beach is int64 and has 0 nan values.
Column amenities_Bicycle rental is int64 and has 0 nan values.
Column amenities_Bicycle tours is int64 and has 0 nan values.
Column amenities_Bicycles available is int64 and has 0 nan values.
Column amenities_Bidet is int64 and has 0 nan values.
Column amenities_Billiards is int64 and has 0 nan values.
Column amenities_Blackout curtains is int64 and has 0 nan values.
Column amenities_Board games / puzzles is int64 and has 0 nan values.
Column amenities_Body wrap is int64 and has 0 nan values.
Column amenities_Books, DVDs, music for children is int64 and has 0 nan values.
Column amenities_Bottled water is int64 and has 0 nan values.
Column amenities_Bowling is int64 and has 0 nan values.
Column amenities_Bowling offsite is int64 and has 0 nan values.
Column amenities_Breakfast available is int64 and has 0 nan values.
Column amenities_Breakfast buffet is int64 and has 0 nan values.
Column amenities_Breakfast in the room is int64 and has 0 nan values.
Column amenities_Bridal suite is int64 and has 0 nan values.
Column amenities_Business Center with Internet Access is int64 and has 0 nan values.
Column amenities_Butler service is int64 and has 0 nan values.
Column amenities_Cable / satellite TV is int64 and has 0 nan values.
Column amenities_Canoeing is int64 and has 0 nan values.
Column amenities_Canoeing offsite is int64 and has 0 nan values.
Column amenities_Car hire is int64 and has 0 nan values.
Column amenities_Casino and Gambling is int64 and has 0 nan values.
Column amenities_Chapel / shrine is int64 and has 0 nan values.
Column amenities_Children's playground is int64 and has 0 nan values.
Column amenities_Children's television networks is int64 and has 0 nan values.
Column amenities_Children Activities (Kid / Family Friendly) is int64 and has 0 nan values.
Column amenities_City view is int64 and has 0 nan values.
Column amenities_Clothes dryer is int64 and has 0 nan values.
Column amenities_Clothes rack is int64 and has 0 nan values.
Column amenities_Coffee / tea maker is int64 and has 0 nan values.
Column amenities_Coffee shop is int64 and has 0 nan values.
Column amenities_Complimentary instant cofffee is int64 and has 0 nan values.
Column amenities_Complimentary tea is int64 and has 0 nan values.
Column amenities_Complimentary toiletries is int64 and has 0 nan values.
Column amenities_Complimentary welcome drink is int64 and has 0 nan values.
Column amenities_Concierge is int64 and has 0 nan values.
Column amenities_Conference facilities is int64 and has 0 nan values.
Column amenities_Convenience store is int64 and has 0 nan values.
Column amenities_Couples massage is int64 and has 0 nan values.
Column amenities_Currency exchange is int64 and has 0 nan values.
Column amenities_Darts is int64 and has 0 nan values.
Column amenities_Desk is int64 and has 0 nan values.
Column amenities_Dining area is int64 and has 0 nan values.
Column amenities_Dishwasher is int64 and has 0 nan values.
Column amenities_Diving is int64 and has 0 nan values.
Column amenities_Doorperson is int64 and has 0 nan values.
Column amenities_Dry cleaning is int64 and has 0 nan values.
Column amenities_DVD / CD player is int64 and has 0 nan values.
Column amenities_Electric blanket is int64 and has 0 nan values.
Column amenities_Electric kettle is int64 and has 0 nan values.
Column amenities_Electric vehicle charging station is int64 and has 0 nan values.
Column amenities_Entertainment staff is int64 and has 0 nan values.
Column amenities_Evening entertainment is int64 and has 0 nan values.
Column amenities_Executive lounge access is int64 and has 0 nan values.
Column amenities_Express check-in / check-out is int64 and has 0 nan values.
Column amenities_Extra long beds is int64 and has 0 nan values.
Column amenities_Facial treatments is int64 and has 0 nan values.
Column amenities_Family rooms is int64 and has 0 nan values.
Column amenities_Fax / photocopying is int64 and has 0 nan values.
Column amenities_Fence around pool is int64 and has 0 nan values.
Column amenities_Fireplace is int64 and has 0 nan values.
Column amenities_First aid kit is int64 and has 0 nan values.
Column amenities_Fishing is int64 and has 0 nan values.
Column amenities_Fitness / spa locker rooms is int64 and has 0 nan values.
Column amenities_Fitness Center with Gym / Workout Room is int64 and has 0 nan values.
Column amenities_Fitness classes is int64 and has 0 nan values.
Column amenities_Flatscreen TV is int64 and has 0 nan values.
Column amenities_Foot bath is int64 and has 0 nan values.
Column amenities_Foot massage is int64 and has 0 nan values.
Column amenities_Free airport transportation is int64 and has 0 nan values.
Column amenities_Free breakfast is int64 and has 0 nan values.
Column amenities_Free High Speed Internet (WiFi) is int64 and has 0 nan values.
Column amenities_Free internet is int64 and has 0 nan values.
Column amenities_Free parking is int64 and has 0 nan values.
Column amenities_Free private parking nearby is int64 and has 0 nan values.
Column amenities_Free public parking nearby is int64 and has 0 nan values.
Column amenities_Free shuttle or taxi services is int64 and has 0 nan values.
Column amenities_Free wifi in the business center is int64 and has 0 nan values.
Column amenities_Free wired internet in the business center is int64 and has 0 nan values.
Column amenities_Full body massage is int64 and has 0 nan values.
Column amenities_Game room is int64 and has 0 nan values.
Column amenities_Gift shop is int64 and has 0 nan values.
Column amenities_Golf course is int64 and has 0 nan values.
Column amenities_Hair dryer is int64 and has 0 nan values.
Column amenities_Hammam is int64 and has 0 nan values.
Column amenities_Hand massage is int64 and has 0 nan values.
Column amenities_Happy hour is int64 and has 0 nan values.
Column amenities_Head massage is int64 and has 0 nan values.
Column amenities_Heated pool is int64 and has 0 nan values.
Column amenities_Highchairs available is int64 and has 0 nan values.
Column amenities_Hiking is int64 and has 0 nan values.
Column amenities_Horseback riding is int64 and has 0 nan values.
Column amenities_Hot tub is int64 and has 0 nan values.
Column amenities_hotel_amenity_free_breakfast is int64 and has 0 nan values.
Column amenities_hotel_amenity_free_internet is int64 and has 0 nan values.
Column amenities_hotel_amenity_internet is int64 and has 0 nan values.
Column amenities_hotel_amenity_wifi is int64 and has 0 nan values.
Column amenities_Housekeeping is int64 and has 0 nan values.
Column amenities_Indoor play area for children is int64 and has 0 nan values.
Column amenities_Indoor pool is int64 and has 0 nan values.
Column amenities_Interconnected rooms available is int64 and has 0 nan values.
Column amenities_Internet is int64 and has 0 nan values.
Column amenities_iPod docking station is int64 and has 0 nan values.
Column amenities_Iron is int64 and has 0 nan values.
Column amenities_Ironing service is int64 and has 0 nan values.
Column amenities_Karaoke is int64 and has 0 nan values.
Column amenities_Kid-friendly buffet is int64 and has 0 nan values.
Column amenities_Kids' meals is int64 and has 0 nan values.
Column amenities_Kids' outdoor play equipment is int64 and has 0 nan values.
Column amenities_Kids club is int64 and has 0 nan values.
Column amenities_Kids pool is int64 and has 0 nan values.
Column amenities_Kids stay free is int64 and has 0 nan values.
Column amenities_Kitchenette is int64 and has 0 nan values.
Column amenities_Kitchenware is int64 and has 0 nan values.
Column amenities_Landmark view is int64 and has 0 nan values.
Column amenities_Laptop safe is int64 and has 0 nan values.
Column amenities_Laundry service is int64 and has 0 nan values.
Column amenities_Makeup services is int64 and has 0 nan values.
Column amenities_Manicure is int64 and has 0 nan values.
Column amenities_Massage is int64 and has 0 nan values.
Column amenities_Massage chair is int64 and has 0 nan values.
Column amenities_Meeting rooms is int64 and has 0 nan values.
Column amenities_Microwave is int64 and has 0 nan values.
Column amenities_Mini golf is int64 and has 0 nan values.
Column amenities_Minibar is int64 and has 0 nan values.
Column amenities_Mosquito net is int64 and has 0 nan values.
Column amenities_Neck massage is int64 and has 0 nan values.
Column amenities_Newspaper is int64 and has 0 nan values.
Column amenities_Nightclub / DJ is int64 and has 0 nan values.
Column amenities_Non-smoking hotel is int64 and has 0 nan values.
Column amenities_Non-smoking rooms is int64 and has 0 nan values.
Column amenities_On-demand movies is int64 and has 0 nan values.
Column amenities_Open-air bath is int64 and has 0 nan values.
Column amenities_Outdoor dining area is int64 and has 0 nan values.
Column amenities_Outdoor fireplace is int64 and has 0 nan values.
Column amenities_Outdoor furniture is int64 and has 0 nan values.
Column amenities_Outdoor pool is int64 and has 0 nan values.
Column amenities_Oven is int64 and has 0 nan values.
Column amenities_Paid internet is int64 and has 0 nan values.
Column amenities_Paid private parking nearby is int64 and has 0 nan values.
Column amenities_Paid private parking on-site is int64 and has 0 nan values.
Column amenities_Paid public parking nearby is int64 and has 0 nan values.
Column amenities_Paid public parking on-site is int64 and has 0 nan values.
Column amenities_Paid wifi is int64 and has 0 nan values.
Column amenities_Parking is int64 and has 0 nan values.
Column amenities_Parking garage is int64 and has 0 nan values.
Column amenities_Patio is int64 and has 0 nan values.
Column amenities_Pedicure is int64 and has 0 nan values.
Column amenities_Personal trainer is int64 and has 0 nan values.
Column amenities_Pets Allowed ( Dog / Pet Friendly ) is int64 and has 0 nan values.
Column amenities_Photo copier / fax In business center is int64 and has 0 nan values.
Column amenities_Picnic area is int64 and has 0 nan values.
Column amenities_Plunge pool is int64 and has 0 nan values.
Column amenities_Pool is int64 and has 0 nan values.
Column amenities_Pool / beach towels is int64 and has 0 nan values.
Column amenities_Pool with view is int64 and has 0 nan values.
Column amenities_Poolside bar is int64 and has 0 nan values.
Column amenities_Private balcony is int64 and has 0 nan values.
Column amenities_Private bathrooms is int64 and has 0 nan values.
Column amenities_Private check-in / check-out is int64 and has 0 nan values.
Column amenities_Private pool is int64 and has 0 nan values.
Column amenities_Public wifi is int64 and has 0 nan values.
Column amenities_Radio is int64 and has 0 nan values.
Column amenities_Refrigerator is int64 and has 0 nan values.
Column amenities_Restaurant is int64 and has 0 nan values.
Column amenities_Rooftop bar is int64 and has 0 nan values.
Column amenities_Rooftop pool is int64 and has 0 nan values.
Column amenities_Rooftop terrace is int64 and has 0 nan values.
Column amenities_Room service is int64 and has 0 nan values.
Column amenities_Safe is int64 and has 0 nan values.
Column amenities_Salon is int64 and has 0 nan values.
Column amenities_Saltwater pool is int64 and has 0 nan values.
Column amenities_Sauna is int64 and has 0 nan values.
Column amenities_Seating area is int64 and has 0 nan values.
Column amenities_Secured parking is int64 and has 0 nan values.
Column amenities_Self-serve laundry is int64 and has 0 nan values.
Column amenities_Separate dining area is int64 and has 0 nan values.
Column amenities_Separate living room is int64 and has 0 nan values.
Column amenities_Shallow end in pool is int64 and has 0 nan values.
Column amenities_Shared bathroom is int64 and has 0 nan values.
Column amenities_Shared kitchen is int64 and has 0 nan values.
Column amenities_Shared lounge / TV area is int64 and has 0 nan values.
Column amenities_Shoeshine is int64 and has 0 nan values.
Column amenities_Shops is int64 and has 0 nan values.
Column amenities_Shuttle bus service is int64 and has 0 nan values.
Column amenities_Smoking rooms available is int64 and has 0 nan values.
Column amenities_Snack bar is int64 and has 0 nan values.
Column amenities_Sofa is int64 and has 0 nan values.
Column amenities_Sofa bed is int64 and has 0 nan values.
Column amenities_Solarium is int64 and has 0 nan values.
Column amenities_Soundproof rooms is int64 and has 0 nan values.
Column amenities_Spa is int64 and has 0 nan values.
Column amenities_Special diet menus is int64 and has 0 nan values.
Column amenities_Steam room is int64 and has 0 nan values.
Column amenities_Stovetop is int64 and has 0 nan values.
Column amenities_Street parking is int64 and has 0 nan values.
Column amenities_Strollers is int64 and has 0 nan values.
Column amenities_Suites is int64 and has 0 nan values.
Column amenities_Sun deck is int64 and has 0 nan values.
Column amenities_Sun loungers / beach chairs is int64 and has 0 nan values.
Column amenities_Sun terrace is int64 and has 0 nan values.
Column amenities_Sun umbrellas is int64 and has 0 nan values.
Column amenities_Swimup bar is int64 and has 0 nan values.
Column amenities_Table tennis is int64 and has 0 nan values.
Column amenities_Taxi service is int64 and has 0 nan values.
Column amenities_Telephone is int64 and has 0 nan values.
Column amenities_Tennis court is int64 and has 0 nan values.
Column amenities_Tennis court offsite is int64 and has 0 nan values.
Column amenities_Tile / marble floor is int64 and has 0 nan values.
Column amenities_Umbrella is int64 and has 0 nan values.
Column amenities_Valet parking is int64 and has 0 nan values.
Column amenities_Vending machine is int64 and has 0 nan values.
Column amenities_Video game console is int64 and has 0 nan values.
Column amenities_VIP room facilities is int64 and has 0 nan values.
Column amenities_Wake-up service / alarm clock is int64 and has 0 nan values.
Column amenities_Walk-in shower is int64 and has 0 nan values.
Column amenities_Walking tours is int64 and has 0 nan values.
Column amenities_Wardrobe / closet is int64 and has 0 nan values.
Column amenities_Washing machine is int64 and has 0 nan values.
Column amenities_Water park is int64 and has 0 nan values.
Column amenities_Water park offsite is int64 and has 0 nan values.
Column amenities_Waterslide is int64 and has 0 nan values.
Column amenities_Waxing services is int64 and has 0 nan values.
Column amenities_Whirlpool bathtub is int64 and has 0 nan values.
Column amenities_Wifi is int64 and has 0 nan values.
Column amenities_Wine / champagne is int64 and has 0 nan values.
Column amenities_Yoga classes is int64 and has 0 nan values.

0

In [110]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

#IterativeImputer: Trains a regression model using high correlated features as predictors and targets the feature of missing values
		#   impute_it = IterativeImputer() #Create object
		#   impute_it.fit_transform(X) #X es el dataframe con los features que se correlacionan mas altos

#first, generate a df with only numerical values
numeric_df = df.select_dtypes(include=['number'])

#check for features with nan values
for column in numeric_df.columns:
    if numeric_df[column].isna().sum() > 0:
        print(column, df[column].isna().sum())

#will use price_min as target
#generate correlation matrix
correlation_matrix = numeric_df.corr()

#check for highly correlated features for price_min
correlation_matrix["price_min"].abs().sort_values(ascending=False)



#will use price_curr_min, prixe_max and amenities_Butler service as predictors
#generate new df for iterativeImputer
iterative_imputer_df = df[["price_curr_min", "price_max", "amenities_Butler service", "price_min"]]

#generate iterative imputer 
impute_it = IterativeImputer()
impute_it.fit_transform(iterative_imputer_df)

location_grade 218
price_curr_min 2224
price_min 1125
price_max 1127
photos 577

array([[ 5578.        , 13819.        ,     0.        ,  5502.        ],
       [ 8778.        , 27946.        ,     0.        , 10949.        ],
       [ 6768.        , 14330.        ,     0.        ,  8381.        ],
       ...,
       [ 5060.55356906, 12708.23253932,     0.        ,  5072.76737459],
       [ 5060.55356906, 12708.23253932,     0.        ,  5072.76737459],
       [ 5060.55356906, 12708.23253932,     0.        ,  5072.76737459]])

In [112]:
from sklearn.impute import KNNImputer
#K-Nearest Neighbors (KNN) Imputation: Replace missing values with the average of values from the k-nearest 2 neighbors 
		#in a multi-dimensional space.

inpute_knn = KNNImputer(n_neighbors = 2)
inpute_knn.fit_transform(numeric_df)

array([[1.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [2.000e+00, 8.800e+01, 1.000e+00, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [3.000e+00, 3.200e+01, 1.000e+00, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [4.597e+03, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [4.598e+03, 0.000e+00, 0.000e+00, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [4.599e+03, 0.000e+00, 0.000e+00, ..., 1.000e+00, 0.000e+00,
        0.000e+00]])

In [8]:
df.shape

(2375, 272)

In [18]:
#Drop columns with more than 15% percentage of missing values.
#For one specific column
#will use price_min for this example

if df["price_min"].isna().sum() / df.shape[0]:
    df.dropna(subset="price_min", inplace=True)

df["price_min"].isna().sum() / df.shape[0]

0.0

In [7]:
#Drop columns with more than 15% percentage of missing values.
		#For all columns

for column in df.columns:
    if df[column].isna().sum() /df.shape[0] > 0.15:
        print("Will drop on", column)
        df.dropna(subset= column, inplace=True)

Will drop con price_curr_min

In [22]:
#Handling Duplicates:
	#Detect all duplicated rows for all columns.

for column in df.columns:
    print("Column", column, "has", df[column].duplicated().sum(), "duplicated values")

Column Unnamed: 0 has 0 duplicated values
Column hotel_url has 0 duplicated values
Column name has 1 duplicated values
Column views has 3449 duplicated values
Column views_binary has 3472 duplicated values
Column score_adjusted has 1319 duplicated values
Column bubble_rating has 3465 duplicated values
Column category_hotel has 3472 duplicated values
Column category_inn has 3472 duplicated values
Column category_specialty has 3472 duplicated values
Column class has 3468 duplicated values
Column class_4_5 has 3472 duplicated values
Column class_3_4_5 has 3472 duplicated values
Column n_reviews has 2725 duplicated values
Column location_grade has 3408 duplicated values
Column discount has 3472 duplicated values
Column discount_perc has 2881 duplicated values
Column price_curr_min has 2235 duplicated values
Column price_min has 2587 duplicated values
Column price_max has 1865 duplicated values
Column award_travellers_choice has 3472 duplicated values
Column award_greenleaders has 3472 duplicated values
Column award_cert_excellence has 3472 duplicated values
Column photos has 2885 duplicated values
Column amenities_24-hour check-in has 3472 duplicated values
Column amenities_24-hour front desk has 3472 duplicated values
Column amenities_24-hour security has 3472 duplicated values
Column amenities_Additional bathroom has 3472 duplicated values
Column amenities_Adults only has 3472 duplicated values
Column amenities_Aerobics has 3472 duplicated values
Column amenities_Air conditioning has 3472 duplicated values
Column amenities_Air purifier has 3472 duplicated values
Column amenities_Airport transportation has 3472 duplicated values
Column amenities_Allergy-free room has 3472 duplicated values
Column amenities_amenity_free_internet_title_ad3 has 3473 duplicated values
Column amenities_ATM on site has 3472 duplicated values
Column amenities_Babysitting has 3472 duplicated values
Column amenities_Baggage storage has 3472 duplicated values
Column amenities_Banquet room has 3472 duplicated values
Column amenities_Bar / lounge has 3472 duplicated values
Column amenities_Bath / shower has 3472 duplicated values
Column amenities_Bathrobes has 3472 duplicated values
Column amenities_BBQ facilities has 3472 duplicated values
Column amenities_Beach has 3472 duplicated values
Column amenities_Bicycle rental has 3472 duplicated values
Column amenities_Bicycle tours has 3472 duplicated values
Column amenities_Bicycles available has 3472 duplicated values
Column amenities_Bidet has 3472 duplicated values
Column amenities_Billiards has 3472 duplicated values
Column amenities_Blackout curtains has 3472 duplicated values
Column amenities_Board games / puzzles has 3472 duplicated values
Column amenities_Body wrap has 3472 duplicated values
Column amenities_Books, DVDs, music for children has 3472 duplicated values
Column amenities_Bottled water has 3472 duplicated values
Column amenities_Bowling has 3472 duplicated values
Column amenities_Bowling offsite has 3472 duplicated values
Column amenities_Breakfast available has 3472 duplicated values
Column amenities_Breakfast buffet has 3472 duplicated values
Column amenities_Breakfast in the room has 3472 duplicated values
Column amenities_Bridal suite has 3472 duplicated values
Column amenities_Business Center with Internet Access has 3472 duplicated values
Column amenities_Butler service has 3472 duplicated values
Column amenities_Cable / satellite TV has 3472 duplicated values
Column amenities_Canoeing has 3472 duplicated values
Column amenities_Canoeing offsite has 3472 duplicated values
Column amenities_Car hire has 3472 duplicated values
Column amenities_Casino and Gambling has 3472 duplicated values
Column amenities_Chapel / shrine has 3472 duplicated values
Column amenities_Children's playground has 3472 duplicated values
Column amenities_Children's television networks has 3472 duplicated values
Column amenities_Children Activities (Kid / Family Friendly) has 3472 duplicated values
Column amenities_City view has 3472 duplicated values
Column amenities_Clothes dryer has 3472 duplicated values
Column amenities_Clothes rack has 3472 duplicated values
Column amenities_Coffee / tea maker has 3472 duplicated values
Column amenities_Coffee shop has 3472 duplicated values
Column amenities_Complimentary instant cofffee has 3472 duplicated values
Column amenities_Complimentary tea has 3472 duplicated values
Column amenities_Complimentary toiletries has 3472 duplicated values
Column amenities_Complimentary welcome drink has 3472 duplicated values
Column amenities_Concierge has 3472 duplicated values
Column amenities_Conference facilities has 3472 duplicated values
Column amenities_Convenience store has 3472 duplicated values
Column amenities_Couples massage has 3472 duplicated values
Column amenities_Currency exchange has 3472 duplicated values
Column amenities_Darts has 3472 duplicated values
Column amenities_Desk has 3472 duplicated values
Column amenities_Dining area has 3472 duplicated values
Column amenities_Dishwasher has 3472 duplicated values
Column amenities_Diving has 3472 duplicated values
Column amenities_Doorperson has 3472 duplicated values
Column amenities_Dry cleaning has 3472 duplicated values
Column amenities_DVD / CD player has 3472 duplicated values
Column amenities_Electric blanket has 3472 duplicated values
Column amenities_Electric kettle has 3472 duplicated values
Column amenities_Electric vehicle charging station has 3472 duplicated values
Column amenities_Entertainment staff has 3472 duplicated values
Column amenities_Evening entertainment has 3472 duplicated values
Column amenities_Executive lounge access has 3472 duplicated values
Column amenities_Express check-in / check-out has 3472 duplicated values
Column amenities_Extra long beds has 3472 duplicated values
Column amenities_Facial treatments has 3472 duplicated values
Column amenities_Family rooms has 3472 duplicated values
Column amenities_Fax / photocopying has 3472 duplicated values
Column amenities_Fence around pool has 3472 duplicated values
Column amenities_Fireplace has 3472 duplicated values
Column amenities_First aid kit has 3472 duplicated values
Column amenities_Fishing has 3472 duplicated values
Column amenities_Fitness / spa locker rooms has 3472 duplicated values
Column amenities_Fitness Center with Gym / Workout Room has 3472 duplicated values
Column amenities_Fitness classes has 3472 duplicated values
Column amenities_Flatscreen TV has 3472 duplicated values
Column amenities_Foot bath has 3472 duplicated values
Column amenities_Foot massage has 3472 duplicated values
Column amenities_Free airport transportation has 3472 duplicated values
Column amenities_Free breakfast has 3472 duplicated values
Column amenities_Free High Speed Internet (WiFi) has 3472 duplicated values
Column amenities_Free internet has 3472 duplicated values
Column amenities_Free parking has 3472 duplicated values
Column amenities_Free private parking nearby has 3472 duplicated values
Column amenities_Free public parking nearby has 3472 duplicated values
Column amenities_Free shuttle or taxi services has 3472 duplicated values
Column amenities_Free wifi in the business center has 3472 duplicated values
Column amenities_Free wired internet in the business center has 3472 duplicated values
Column amenities_Full body massage has 3472 duplicated values
Column amenities_Game room has 3472 duplicated values
Column amenities_Gift shop has 3472 duplicated values
Column amenities_Golf course has 3472 duplicated values
Column amenities_Hair dryer has 3472 duplicated values
Column amenities_Hammam has 3472 duplicated values
Column amenities_Hand massage has 3472 duplicated values
Column amenities_Happy hour has 3472 duplicated values
Column amenities_Head massage has 3472 duplicated values
Column amenities_Heated pool has 3472 duplicated values
Column amenities_Highchairs available has 3472 duplicated values
Column amenities_Hiking has 3472 duplicated values
Column amenities_Horseback riding has 3472 duplicated values
Column amenities_Hot tub has 3472 duplicated values
Column amenities_hotel_amenity_free_breakfast has 3473 duplicated values
Column amenities_hotel_amenity_free_internet has 3473 duplicated values
Column amenities_hotel_amenity_internet has 3473 duplicated values
Column amenities_hotel_amenity_wifi has 3473 duplicated values
Column amenities_Housekeeping has 3472 duplicated values
Column amenities_Indoor play area for children has 3472 duplicated values
Column amenities_Indoor pool has 3472 duplicated values
Column amenities_Interconnected rooms available has 3472 duplicated values
Column amenities_Internet has 3472 duplicated values
Column amenities_iPod docking station has 3472 duplicated values
Column amenities_Iron has 3472 duplicated values
Column amenities_Ironing service has 3472 duplicated values
Column amenities_Karaoke has 3472 duplicated values
Column amenities_Kid-friendly buffet has 3472 duplicated values
Column amenities_Kids' meals has 3472 duplicated values
Column amenities_Kids' outdoor play equipment has 3472 duplicated values
Column amenities_Kids club has 3472 duplicated values
Column amenities_Kids pool has 3472 duplicated values
Column amenities_Kids stay free has 3472 duplicated values
Column amenities_Kitchenette has 3472 duplicated values
Column amenities_Kitchenware has 3472 duplicated values
Column amenities_Landmark view has 3472 duplicated values
Column amenities_Laptop safe has 3472 duplicated values
Column amenities_Laundry service has 3472 duplicated values
Column amenities_Makeup services has 3472 duplicated values
Column amenities_Manicure has 3472 duplicated values
Column amenities_Massage has 3472 duplicated values
Column amenities_Massage chair has 3472 duplicated values
Column amenities_Meeting rooms has 3472 duplicated values
Column amenities_Microwave has 3472 duplicated values
Column amenities_Mini golf has 3472 duplicated values
Column amenities_Minibar has 3472 duplicated values
Column amenities_Mosquito net has 3472 duplicated values
Column amenities_Neck massage has 3472 duplicated values
Column amenities_Newspaper has 3472 duplicated values
Column amenities_Nightclub / DJ has 3472 duplicated values
Column amenities_Non-smoking hotel has 3472 duplicated values
Column amenities_Non-smoking rooms has 3472 duplicated values
Column amenities_On-demand movies has 3472 duplicated values
Column amenities_Open-air bath has 3472 duplicated values
Column amenities_Outdoor dining area has 3472 duplicated values
Column amenities_Outdoor fireplace has 3472 duplicated values
Column amenities_Outdoor furniture has 3472 duplicated values
Column amenities_Outdoor pool has 3472 duplicated values
Column amenities_Oven has 3472 duplicated values
Column amenities_Paid internet has 3472 duplicated values
Column amenities_Paid private parking nearby has 3472 duplicated values
Column amenities_Paid private parking on-site has 3472 duplicated values
Column amenities_Paid public parking nearby has 3472 duplicated values
Column amenities_Paid public parking on-site has 3472 duplicated values
Column amenities_Paid wifi has 3472 duplicated values
Column amenities_Parking has 3472 duplicated values
Column amenities_Parking garage has 3472 duplicated values
Column amenities_Patio has 3472 duplicated values
Column amenities_Pedicure has 3472 duplicated values
Column amenities_Personal trainer has 3472 duplicated values
Column amenities_Pets Allowed ( Dog / Pet Friendly ) has 3472 duplicated values
Column amenities_Photo copier / fax In business center has 3472 duplicated values
Column amenities_Picnic area has 3472 duplicated values
Column amenities_Plunge pool has 3472 duplicated values
Column amenities_Pool has 3472 duplicated values
Column amenities_Pool / beach towels has 3472 duplicated values
Column amenities_Pool with view has 3472 duplicated values
Column amenities_Poolside bar has 3472 duplicated values
Column amenities_Private balcony has 3472 duplicated values
Column amenities_Private bathrooms has 3472 duplicated values
Column amenities_Private check-in / check-out has 3472 duplicated values
Column amenities_Private pool has 3472 duplicated values
Column amenities_Public wifi has 3472 duplicated values
Column amenities_Radio has 3472 duplicated values
Column amenities_Refrigerator has 3472 duplicated values
Column amenities_Restaurant has 3472 duplicated values
Column amenities_Rooftop bar has 3472 duplicated values
Column amenities_Rooftop pool has 3472 duplicated values
Column amenities_Rooftop terrace has 3472 duplicated values
Column amenities_Room service has 3472 duplicated values
Column amenities_Safe has 3472 duplicated values
Column amenities_Salon has 3472 duplicated values
Column amenities_Saltwater pool has 3472 duplicated values
Column amenities_Sauna has 3472 duplicated values
Column amenities_Seating area has 3472 duplicated values
Column amenities_Secured parking has 3472 duplicated values
Column amenities_Self-serve laundry has 3472 duplicated values
Column amenities_Separate dining area has 3472 duplicated values
Column amenities_Separate living room has 3472 duplicated values
Column amenities_Shallow end in pool has 3472 duplicated values
Column amenities_Shared bathroom has 3472 duplicated values
Column amenities_Shared kitchen has 3472 duplicated values
Column amenities_Shared lounge / TV area has 3472 duplicated values
Column amenities_Shoeshine has 3472 duplicated values
Column amenities_Shops has 3472 duplicated values
Column amenities_Shuttle bus service has 3472 duplicated values
Column amenities_Smoking rooms available has 3472 duplicated values
Column amenities_Snack bar has 3472 duplicated values
Column amenities_Sofa has 3472 duplicated values
Column amenities_Sofa bed has 3472 duplicated values
Column amenities_Solarium has 3472 duplicated values
Column amenities_Soundproof rooms has 3472 duplicated values
Column amenities_Spa has 3472 duplicated values
Column amenities_Special diet menus has 3472 duplicated values
Column amenities_Steam room has 3472 duplicated values
Column amenities_Stovetop has 3472 duplicated values
Column amenities_Street parking has 3472 duplicated values
Column amenities_Strollers has 3472 duplicated values
Column amenities_Suites has 3472 duplicated values
Column amenities_Sun deck has 3472 duplicated values
Column amenities_Sun loungers / beach chairs has 3472 duplicated values
Column amenities_Sun terrace has 3472 duplicated values
Column amenities_Sun umbrellas has 3472 duplicated values
Column amenities_Swimup bar has 3472 duplicated values
Column amenities_Table tennis has 3472 duplicated values
Column amenities_Taxi service has 3472 duplicated values
Column amenities_Telephone has 3472 duplicated values
Column amenities_Tennis court has 3472 duplicated values
Column amenities_Tennis court offsite has 3472 duplicated values
Column amenities_Tile / marble floor has 3472 duplicated values
Column amenities_Umbrella has 3472 duplicated values
Column amenities_Valet parking has 3472 duplicated values
Column amenities_Vending machine has 3472 duplicated values
Column amenities_Video game console has 3472 duplicated values
Column amenities_VIP room facilities has 3472 duplicated values
Column amenities_Wake-up service / alarm clock has 3472 duplicated values
Column amenities_Walk-in shower has 3472 duplicated values
Column amenities_Walking tours has 3472 duplicated values
Column amenities_Wardrobe / closet has 3472 duplicated values
Column amenities_Washing machine has 3472 duplicated values
Column amenities_Water park has 3472 duplicated values
Column amenities_Water park offsite has 3472 duplicated values
Column amenities_Waterslide has 3472 duplicated values
Column amenities_Waxing services has 3472 duplicated values
Column amenities_Whirlpool bathtub has 3472 duplicated values
Column amenities_Wifi has 3472 duplicated values
Column amenities_Wine / champagne has 3472 duplicated values
Column amenities_Yoga classes has 3472 duplicated values

In [35]:
df.shape

(2262, 272)

In [37]:
#Handling Duplicates:
	#Remove all duplicated rows for all columns.

print("Shape befor dropna", df.shape)

df.dropna(inplace=True)

print("Shape after dropna", df.shape)

Shape befor dropna (4599, 272)
Shape after dropna (2262, 272)

In [63]:
#Handling Duplicates:	
    #Detect and remove all duplicated rows for a group of columns.

print("Before shape:", df[["price_min", "price_max", "views_binary"]].shape)

df.drop_duplicates(subset =["price_min", "price_max", "views_binary"], inplace=True)

print("After drop duplicates shape:" ,df[["price_min", "price_max", "views_binary"]].shape)

Before shape: (3372, 3)
After drop duplicates shape: (3372, 3)

In [70]:
#Handling Duplicates:
	#Detect and remove all duplicated rows for all columns.
	#Detect and remove all duplicated rows for a group of columns. Drop all except first occurrence

print("Before shape:", df[["price_min", "price_max", "views_binary"]].shape)

df.drop_duplicates(subset= ["price_min", "price_max", "views_binary"], inplace=True, keep="first")

print("After dropna shape:" ,df[["price_min", "price_max", "views_binary"]].shape)

Before shape: (4599, 3)
After dropna shape: (3372, 3)

In [107]:
#Data Type Conversion:
	#Convert all numeric columns to string

import numpy as np

#print number of numerical columns before converting
print("Number of numerical columns before convertion is", df.select_dtypes(include=np.number).shape[1])

#generate a list of numeric columns
columns_list = list(df.select_dtypes(include=np.number))

for count, item in enumerate (columns_list):
    df[item] = df[item].astype(str)

#print number of numerical columns after converting
print("Number of numerical columns after convertion is", df.select_dtypes(include=np.number).shape[1])

Number of numerical columns before convertion is 269
Number of numerical columns after convertion is 0

In [109]:
#Data Type Conversion:
	#Convert one numerical column to string

print("Before convertion, price_min is", df["price_min"].dtypes)

df["price_min"] = df["price_min"].astype(str)

print("After convertion, price_min is", df["price_min"].dtypes)

Before convertion, price_min is float64
After convertion, price_min is object

In [170]:
#Data Type Conversion
    #Convert any yes/no column to categorical data

#will use views_binary as categorical column
print("Before:" ,df["views_binary"].head(10))

#convert column to string
df["views_binary"] = df["views_binary"].astype(str)

#map 0 for no and 1 for yes
df["views_binary"] = df["views_binary"].map({"0" : "no", "1" : "yes"})

#check result
print("\nAfter:", df["views_binary"].head(10))

Before: 0    0
1    1
2    1
3    1
4    0
5    1
6    0
7    1
8    1
9    1
Name: views_binary, dtype: int64

After: 0     no
1    yes
2    yes
3    yes
4     no
5    yes
6     no
7    yes
8    yes
9    yes
Name: views_binary, dtype: object

In [230]:
#Renaming Columns:
	#Rename column by name

#show column names
print(df.columns)

#change hotel_url to hotel_url_adrress
df.rename(columns={"hotel_url" : "hotel_url_address"}, inplace=True)

#check result
print("\n", df.columns)

Index(['Unnamed: 0', 'hotel_url', 'name', 'views', 'views_binary',
       'score_adjusted', 'bubble_rating', 'category_hotel', 'category_inn',
       'category_specialty',
       ...
       'amenities_Wardrobe / closet', 'amenities_Washing machine',
       'amenities_Water park', 'amenities_Water park offsite',
       'amenities_Waterslide', 'amenities_Waxing services',
       'amenities_Whirlpool bathtub', 'amenities_Wifi',
       'amenities_Wine / champagne', 'amenities_Yoga classes'],
      dtype='object', length=272)

 Index(['Unnamed: 0', 'hotel_url_address', 'name', 'views', 'views_binary',
       'score_adjusted', 'bubble_rating', 'category_hotel', 'category_inn',
       'category_specialty',
       ...
       'amenities_Wardrobe / closet', 'amenities_Washing machine',
       'amenities_Water park', 'amenities_Water park offsite',
       'amenities_Waterslide', 'amenities_Waxing services',
       'amenities_Whirlpool bathtub', 'amenities_Wifi',
       'amenities_Wine / champagne', 'amenities_Yoga classes'],
      dtype='object', length=272)

In [251]:
#Renaming Columns:
	#Rename a list of columns

#print column names
print(df.columns)

#create list of columns to be renamed
original_columns = ["name", "views", "views_binary"]
new_columns = ["name_x", "views_x", "views_binary_x"]

#create dictionary from the two lists above using dict comprehension
dict = {original_columns[i] : new_columns[i] for i in range(len(original_columns))}

df.rename(columns=dict, inplace=True)

#check for result
print("\n", df.columns)

Index(['Unnamed: 0', 'hotel_url_address', 'name_x', 'views_x',
       'views_binary_x', 'score_adjusted', 'bubble_rating', 'category_hotel',
       'category_inn', 'category_specialty',
       ...
       'amenities_Wardrobe / closet', 'amenities_Washing machine',
       'amenities_Water park', 'amenities_Water park offsite',
       'amenities_Waterslide', 'amenities_Waxing services',
       'amenities_Whirlpool bathtub', 'amenities_Wifi',
       'amenities_Wine / champagne', 'amenities_Yoga classes'],
      dtype='object', length=272)

 Index(['Unnamed: 0', 'hotel_url_address', 'name_x', 'views_x',
       'views_binary_x', 'score_adjusted', 'bubble_rating', 'category_hotel',
       'category_inn', 'category_specialty',
       ...
       'amenities_Wardrobe / closet', 'amenities_Washing machine',
       'amenities_Water park', 'amenities_Water park offsite',
       'amenities_Waterslide', 'amenities_Waxing services',
       'amenities_Whirlpool bathtub', 'amenities_Wifi',
       'amenities_Wine / champagne', 'amenities_Yoga classes'],
      dtype='object', length=272)

In [254]:
#Renaming Columns:
    #Rename all columns to lowercase

#show column names (first column "Unnamed 0" is capital)
print(df.columns)

#convert to lowecase
df.rename(str.lower, axis="columns", inplace=True)

#check result 
print("\n", df.columns)

Index(['Unnamed: 0', 'hotel_url', 'name', 'views', 'views_binary',
       'score_adjusted', 'bubble_rating', 'category_hotel', 'category_inn',
       'category_specialty',
       ...
       'amenities_Wardrobe / closet', 'amenities_Washing machine',
       'amenities_Water park', 'amenities_Water park offsite',
       'amenities_Waterslide', 'amenities_Waxing services',
       'amenities_Whirlpool bathtub', 'amenities_Wifi',
       'amenities_Wine / champagne', 'amenities_Yoga classes'],
      dtype='object', length=272)

 Index(['unnamed: 0', 'hotel_url', 'name', 'views', 'views_binary',
       'score_adjusted', 'bubble_rating', 'category_hotel', 'category_inn',
       'category_specialty',
       ...
       'amenities_wardrobe / closet', 'amenities_washing machine',
       'amenities_water park', 'amenities_water park offsite',
       'amenities_waterslide', 'amenities_waxing services',
       'amenities_whirlpool bathtub', 'amenities_wifi',
       'amenities_wine / champagne', 'amenities_yoga classes'],
      dtype='object', length=272)

In [282]:
#Standardizing Text Data:
	#Standardize text data in any column converting strings to lowercase 

#print string column names
df.select_dtypes(include="O")

#print first rows
print("Before:", df["name"].head())

#will use name column
df["name"] = df["name"].str.lower()

#check for result
print("\nAfter:", df["name"].head())

Before: 0    Casa Mia in Trastevere
1            Hotel Artemide
2    A.Roma Lifestyle Hotel
3             iQ Hotel Roma
4              The Guardian
Name: name, dtype: object

After: 0    casa mia in trastevere
1            hotel artemide
2    a.roma lifestyle hotel
3             iq hotel roma
4              the guardian
Name: name, dtype: object